name: Test

on: [push]

jobs:
  lint:
    strategy:
      matrix:
        toxenv: [isort, flake8, black]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox - ${{ matrix.toxenv }}
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox

  test:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9, "3.10"]
        django-version: [18, 19, 110, 111, 20, 21, 22, 30, 31, 32, 40, main]
        experimental: [false]

        # Allow failures on Django main branch test.
        include:
          - python-version: "3.10"
            django-version: main
            experimental: true

        exclude:
          # Python 3.5
          - python-version: 3.5
            django-version: 30
          - python-version: 3.5
            django-version: 31
          - python-version: 3.5
            django-version: 32
          - python-version: 3.5
            django-version: 40
          - python-version: 3.5
            django-version: main

          # Python 3.6
          - python-version: 3.6
            django-version: 18
          - python-version: 3.6
            django-version: 19
          - python-version: 3.6
            django-version: 110
          - python-version: 3.6
            django-version: 40
          - python-version: 3.6
            django-version: main

          # Python 3.7
          - python-version: 3.7
            django-version: 18
          - python-version: 3.7
            django-version: 19
          - python-version: 3.7
            django-version: 110
          - python-version: 3.7
            django-version: 111
          - python-version: 3.7
            django-version: 40
          - python-version: 3.7
            django-version: main


          # Python 3.8
          - python-version: 3.8
            django-version: 18
          - python-version: 3.8
            django-version: 19
          - python-version: 3.8
            django-version: 110
          - python-version: 3.8
            django-version: 111
          - python-version: 3.8
            django-version: 111
          - python-version: 3.8
            django-version: 20
          - python-version: 3.8
            django-version: 21
          - python-version: 3.8
            django-version: main

          # Python 3.9
          - python-version: "3.9"
            django-version: 18
          - python-version: "3.9"
            django-version: 19
          - python-version: "3.9"
            django-version: 110
          - python-version: "3.9"
            django-version: 111
          - python-version: "3.9"
            django-version: 111
          - python-version: "3.9"
            django-version: 20
          - python-version: "3.9"
            django-version: 21
          - python-version: "3.9"
            django-version: main

          # Python 3.10
          - python-version: "3.10"
            django-version: 18
          - python-version: "3.10"
            django-version: 19
          - python-version: "3.10"
            django-version: 110
          - python-version: "3.10"
            django-version: 111
          - python-version: "3.10"
            django-version: 111
          - python-version: "3.10"
            django-version: 20
          - python-version: "3.10"
            django-version: 21
          - python-version: "3.10"
            django-version: 21
          - python-version: "3.10"
            django-version: 22
          - python-version: "3.10"
            django-version: 30
          - python-version: "3.10"
            django-version: 31
          - python-version: "3.10"
            django-version: main


    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox - Python ${{ matrix.python-version}}, Django ${{ matrix.django-version }}
        env:
          TOXENV: py-dj${{ matrix.django-version }}
        run: tox

  build:
    continue-on-error: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: python -m pip install --upgrade setuptools wheel twine

      - name: Build Python packages
        run: python setup.py bdist_wheel sdist

      - name: twine check
        run: twine check dist/*

      - name: Upload Python packages artifact
        uses: actions/upload-artifact@v1
        with:
          name: Python Packages
          path: dist
